### ISSUE TITLE
How to setup the compile environment

### ISSUE THREAD

**Issue by edwardrf** [aloksinha2001/Linux3188#10]
1. Is the cross compiler come with ubuntu good enough? I installed using
   sudo apt-get install gcc-arm-linux-gnueabi
2. There is a sz command at the end of the build script make_kernel_ruikemei.sh, is that the zmodem program or some other compressor?

**Comment by aloksinha2001** [comment]
You can ignore/remove the sz command.

I will update a make file as well on to the system.
