### ISSUE TITLE
Make clean gives error

### ISSUE THREAD

**Issue by edwardrf** [aloksinha2001/Linux3188#12]
```
Linux3188/drivers/gpu/drm/mali_drm/Makefile:65: *** No KDIR found for platform ct11mp.  Stop.
make[3]: *** [drivers/gpu/drm/mali_drm] Error 2
make[2]: *** [drivers/gpu/drm] Error 2
make[1]: *** [drivers/gpu] Error 2
make: *** [_clean_drivers] Error 2
```

Seems like the make file for mali_drm is not configured properly

**Comment by aloksinha2001** [comment]
Something else would be the problem - we are able to compile effectively.

**Comment by edwardrf** [comment]
I am able to compile the kernel if I do a make kernel.img first.

Have you tried

```
make clean
```

For 2 consecutive times?

**Comment by edwardrf** [comment]
also the KDIR_CONFIGURATION file is referencing hardcoded non-existing location

```
/projects/pr297/linux/eb_ct11mp/current/linux
```

Is it suppose to be like that? Or there are missing files

**Comment by aloksinha2001** [comment]
Yes - make clean DOES give error - in the second time... not able to
resolve that yet.

Alok

---

http://www.linkedin.com/profile/view?id=12406006&trk=tab_pro
http://aloksinha2001.blogspot.in

**Comment by aloksinha2001** [comment]
There are possibly missing files - but not relevant to us for this platform.

Alok

---

http://www.linkedin.com/profile/view?id=12406006&trk=tab_pro
http://aloksinha2001.blogspot.in

**Comment by usumfabricae** [comment]
Did you try setting environment variable  KDIR to your local kernel path than make clean ?

**Comment by edwardrf** [comment]
```
make KDIR=./ clean
```

seemed to work.
