### ISSUE TITLE
Picuntu Site is down for days, no where to download SD card image

### ISSUE THREAD

**Issue by edwardrf** [aloksinha2001/Linux3188#14]
Hi Alok,

It seems the picuntu site is down for some time, is there any hardware issue?

**Comment by aloksinha2001** [comment]
Its up now... :)

Alok

---

http://www.linkedin.com/profile/view?id=12406006&trk=tab_pro
http://aloksinha2001.blogspot.in

**Comment by edwardrf** [comment]
Thanks! The SD card download URL is not working still though.

http://download.g8.net/picuntu/picuntu-linuxroot-0.9-RC2.1.tgz

**Comment by aloksinha2001** [comment]
let me check.

---

http://www.linkedin.com/profile/view?id=12406006&trk=tab_pro
http://aloksinha2001.blogspot.in
